### ISSUE TITLE
Part-Cooling fan speed?

### ISSUE THREAD

**Issue by TypQxQ** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#13]
Is the PartCoolingFan 12V in maximum or is it limited as in original?
Couldn't say by the info in Readme.

**Comment by newPOPE** [comment]
Do you want to change it or?

**Comment by derhopp** [comment]
There is no need to change anything as this fork used the full 12V like the mainstream Marlin. 

There was no intention to fully clone the original firmware of the printer.

**Comment by TypQxQ** [comment]
Thank you. Wanted to be sure it was 12V.
