### ISSUE TITLE
Pre-heat causes Z raise

### ISSUE THREAD

**Issue by ollie-campbell** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#21]
### Description

Using the Pre-heat options via the LCD causes the Z axis to raise.

### Steps to Reproduce

1. Tools
2. Pre-heat
3. Pre-heat PLA

**Expected behavior:** [What you expect to happen]
Just the hotbed and nozzle to heat to the set temperatures.

**Actual behavior:** [What actually happens]
The hotbed and nozzle do pre-heat, but the Z axis raises.
[Configuration.zip](https://github.com/derhopp/Marlin-with-Anycubic-i3-Mega-TFT/files/2455148/Configuration.zip)

**Comment by newPOPE** [comment]
Is it only for PLA preheat?

I think that is normal for Z raise. One of the reason can be that hot filament can drop down from nozzle. Why is the issue for you?

**Comment by ollie-campbell** [comment]
Hello,
I haven't tried the Pre-heat for ABS but will try when my print has finished.

It is not an issue, it is just different from the standard firmware that ships with the printer and presumed that it must be a bug.

**Comment by newPOPE** [comment]
:) for me is a good access from printer => no issue. Maybe @derhopp will know more.

**Comment by derhopp** [comment]
This feature is meant to protect your bed surface. If z<10 and you enter preheat on the TFT the axis rises.  

Working as intended —> no bug. Closed.

**Comment by ollie-campbell** [comment]
Ahh I see. I looked at the differences listed on Github and didn't see it mentioned so thought the worst! 

Thanks for the detail 👍
