### ISSUE TITLE
Does M600 (filament change) work with this firmware and i3 Mega?

### ISSUE THREAD

**Issue by CaptInsano** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#22]
I am aware that M600 is listed as an available command since Marlin 1.1.0 here:

http://marlinfw.org/docs/gcode/M600.html

Given that this code base is altered to work with the Anycubic i3 Mega, does it work here? If so, is it enabled by default? 

I am new to the i3 Mega and looking to try this firmware and try some multicolour prints via the Octoprint Multicolour plugin:

https://github.com/MoonshineSG/OctoPrint-MultiColors

Thanks for all your work in bring improved firmware to the i3 Mega while keeping the TFT functional!

**Comment by derhopp** [comment]
Hi,

M600 does work if you enable "NOZZLE_PARK_FEATURE" (Configuration.h), "ADVANCED_PAUSE_FEATURE" (Configuration_adv.h) and "EMERGENCY_PARSER" (Configuration_adv.h).

You can't interact through the display for that feature, but you can use the console.

Regards
Christian

**Comment by newPOPE** [comment]
@derhopp is it working? But I tried it (enable that things) and printer did nothing. When I send M600 command console say "ok" and did nothing. Is there any other issue? (default tft display not LCD).
