### ISSUE TITLE
m600

### ISSUE THREAD

**Issue by ondrax1** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#24]
Hello, i have question. I have Anycubic with derhopp marlin 1.1.x I update original FW, becouse i need function m600 and changing filament. But i have problem with this. I setup
#define ADVANCED_PAUSE_FEATURE

and

#define NOZZLE_PARK_FEATURE

After check, arduino ide wrote me #error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller or EMERGENCY_PARSER." And i setup function Emergency parser. After that i flash this FW to my printer. Pausing is working! (fantastic) but i dont know how i can continue print, after change filament. If i try make pause, temperatures goes to 0 and pring progress is stopped.

video here: https://youtu.be/RSgZyg1jOtM

(link here https://github.com/derhopp/Marlin-with-Anycubic-i3-Mega-TFT)

Sorry for my bad english.

Thank you so much

**Comment by newPOPE** [comment]
I think that display fw doesn't support m600 feature although printer fw support that.
Did you try some workaround? Maybe somethink like this:

- use m600
- when nozzle goes to pause mode
- change filament
- click pause on display
- click continue (display support)

but this is only idea, maybe it will not work.

**Comment by derhopp** [comment]
Actually it does work but not through the display.

You have to send a M108 through the terminal to continue.

In case you connected your printer with OctoPrint, you have to send (one or two) FakeAcknowledgements in between.

**Comment by ondrax1** [comment]
Hello, i use pronter face. M600 in gcode make me pause, i change filament. Send m108 via ptonter face and problem 
![image](https://user-images.githubusercontent.com/45208636/48863172-baeaeb00-edc8-11e8-9f30-bfbc6ceaa3dd.png)

**Comment by ondrax1** [comment]
enable "NOZZLE_PARK_FEATURE" (Configuration.h), "ADVANCED_PAUSE_FEATURE" (Configuration_adv.h) and "EMERGENCY_PARSER" (Configuration_adv.h).
