### ISSUE TITLE
pins_TRIGORILLA_14.h REPRAP_DISCOUNT_SMART_CONTROLLER wrong pins for BTN_ENx

### ISSUE THREAD

**Issue by pribasv** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#25]
On file pins_TRIGORILLA_14.h:

		#ifdef REPRAP_DISCOUNT_SMART_CONTROLLER
			#define BEEPER_PIN 31

			#define BTN_EN1 33
			#define BTN_EN2 33
			#define BTN_ENC 35

BTN_EN1 and BTN_EN2 points to the same pin so the rotary controller of a REPRAP SMART CONTROLLER (Also on the FULL GRAPHIC CONTROLLER) will be irresponsive.

I've reproduced the issue on a Anycubic i3 Mega Ultrabase:

1. Detach the i3 Mega TFT Switch board from the Trigorilla board.
2. Wire ENDSTOP pins, thermal sensors pins, power and 5v from the Trigorilla board to the detached PCB.
3. Unplug TFT and SD reader from the detached PCB.
4. Plug REPRAPDISCOUNT FULL GRAPHIC SMART CONTROLLER on Trigorilla EXP1 and EXP2 ports.
5. Enable REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER and disable ANYCUBIC_TFT_MODEL, ANYCUBIC_TFT_DEBUG on Marlin, compile and flash.

After flashing the rotary controller will be irresponsive as it reports both directions simultaneusly.

The issue is solved changing BTN_EN1 or BTN_EN2 to pin 31.

**Comment by derhopp** [comment]
Thanks for the PR. I have fixed it in all relevant branches.
