### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by TigerClaw33** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#27]
Hi, 
I have a general qestion about Marlin. I have a Anycubic I3 Mega with TriGo.Board. I also want to build my own Prusa I3 Clone with Arduino Board. 

If I want to install newer firmware for my Anycubic can I use every Marlin version or only specific Anycubic I3 Mega firmware? 

Or let's say I want to remove the TriGorila Board from my Anycubic and put an other board inside. Do I have to use the anycubic firmware or general firmware or specific firmware for the Arduino? I dont' understand it exactly.

**Comment by derhopp** [comment]
You can use a vanilla Marlin, if you put you board in a different printer.  This fork just adds the capabilities for the display of the Anycubic I3 Mega.
