### ISSUE TITLE
Get back full buzzer functionality

### ISSUE THREAD

**Issue by RolandW89** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#29]
Hello DerHopp, great work with the Firmware. Working very good.

I think most peoples are happy about disabled buzzer but is there a method to enable it again in config? I like some notifications from it like beep on filament runout or endstop.

**Comment by derhopp** [comment]
Unfortunately it‘s not in the code. Thus, there is no configuration option for it.

**Comment by RolandW89** [comment]
Thanks for the fast answer.
