### ISSUE TITLE
Single Z endstop

### ISSUE THREAD

**Issue by wasback** [derhopp/Marlin-with-Anycubic-i3-Mega-TFT#31]
Hello my dear,

I have the old Mega I3, with the single Z endstop, im trying to get a BLTouch to work.
How can I change the config ? Thanks

**Comment by derhopp** [comment]
Hi,

You have to disable Dual-Z-Steppers...
Configuration_adv.h: comment out #define Z_DUAL_STEPPER_DRIVERS

To enable BLTouch modify (never tried it my self... I use piezo z-probes)...
Configuration.h: 
- comment in //#define BLTOUCH
- set the correct x- and y-probe-offsets (X_PROBE_OFFSET_FROM_EXTRUDER, Y_PROBE_OFFSET_FROM_EXTRUDER)

Best regards
